#!/bin/bash
# 1. このファイルを $HOME/.config/git-hooks/pre-hookに移動
# 2. chmod +x $HOME/.config/git-hooks
# 3. git config --global core.hooksPath $HOME/.config/git-hooks

_exec_localhook(){
  GIT_ROOT=$(git rev-parse --show-superproject-working-tree --show-toplevel | head -1)
  HOOK_NAME=$(basename $0)
  LOCAL_HOOK="${GIT_ROOT}/.git/hooks/${HOOK_NAME}"
  if [ -e $LOCAL_HOOK ]; then
    source $LOCAL_HOOK
  fi
}

allow_push(){
    org=$1
    REMOTE_URL=$2
    echo "========================================================="
    echo "[Allow push: ${org}"]
    echo "Remote url is $REMOTE_URL"
    echo "========================================================="
    _exec_localhook
    exit 0
}

deny_push(){
    REMOTE_URL=$1
    echo "========================================================="
    echo "[Deny push]"
    echo "Remote url is $REMOTE_URL"
    echo "========================================================="
    exit 1
}

REMOTE_URL=$(git config --get remote.origin.url)
ALLOW_PUSH_ORGS=(xxx)

for org in "${ALLOW_PUSH_ORGS[@]}"; do
  if [[ $REMOTE_URL == "https://github.com/${org}/"* ]] || [[ $REMOTE_URL == "git@github.com:${org}/"* ]];then
    allow_push $org $REMOTE_URL
  fi
done

deny_push $REMOTE_URL
