alias cdoc="cd $HOME/docs/doc"
export GIST_DIR="$HOME/src/github.com/t-akira012/aki012/gists"
export ALL_GIST_INDEX=''
export CCC_DIR=''
export MEMO_DIR="$HOME/docs/doc"
export TERM_COLOR_MODE='DARK'
export NVIM_COLOR_DARK='vim-material'
export NVIM_COLOR_LIGHT='vim-material'
# export BROWSER="open -a /Applications/Firefox\ Developer\ Edition.app/"
# export BROWSER="open -a /Applications/Google\ Chrome.app/"
