working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.normal]
family = "Cica"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
title = "Alacritty"

[window.dimensions]
columns = 220
lines = 65

[window.padding]
x = 10
y = 2
